#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CHESTER_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_DIR=""; MODE="all"
while [ $# -gt 0 ]; do
  case "$1" in
    --root) CHESTER_ROOT="$(cd "$2" && pwd)"; shift 2 ;;
    --output-dir) OUT_DIR="$2"; shift 2 ;;
    --agents-only) MODE="agents"; shift ;;
    --catalog-only) MODE="catalog"; shift ;;
    *) echo "chester-generate-agents: unknown arg: $1" >&2; exit 2 ;;
  esac
done
[ -n "$OUT_DIR" ] || OUT_DIR="$CHESTER_ROOT"
MANIFEST="$CHESTER_ROOT/agents/manifest.json"
command -v jq >/dev/null 2>&1 || { echo "chester-generate-agents: jq required" >&2; exit 3; }
[ -f "$MANIFEST" ] || { echo "chester-generate-agents: manifest not found: $MANIFEST" >&2; exit 3; }

HEADER='<!-- generated by bin/chester-generate-agents — edit canonical sources under agents/sources/, not this file -->'

# extract_section FILE "Heading" → body lines between "## Heading" and the next "## " (exclusive),
# with leading blank lines after the heading stripped (F6) so a blank line under the heading
# does not produce a double blank in the assembled output.
extract_section() {
  awk -v h="## $2" '
    $0==h { flag=1; started=0; next }
    flag && /^## / { flag=0 }
    flag {
      if (!started && $0 ~ /^[[:space:]]*$/) next
      started=1
      print
    }' "$1"
}

emit_agent() {
  local idx="$1" out frontmatter nfrag i ftype
  out="$(jq -r ".agents[$idx].output" "$MANIFEST")"
  frontmatter="$(jq -r ".agents[$idx].frontmatter" "$MANIFEST")"
  local dest="$OUT_DIR/$out"; mkdir -p "$(dirname "$dest")"
  local tmp; tmp="$(mktemp)"
  trap 'rm -f "$tmp"' RETURN  # clean the temp file on any exit from this function (incl. fragment-not-found)
  {
    printf '%s\n' "$HEADER"
    printf '%s\n' "$frontmatter"
    nfrag="$(jq -r ".agents[$idx].fragments | length" "$MANIFEST")"
    for (( i=0; i<nfrag; i++ )); do
      ftype="$(jq -r ".agents[$idx].fragments[$i] | if type==\"string\" then \"file\" else \"section\" end" "$MANIFEST")"
      if [ "$ftype" = "file" ]; then
        local fpath; fpath="$(jq -r ".agents[$idx].fragments[$i]" "$MANIFEST")"
        [ -f "$CHESTER_ROOT/$fpath" ] || { echo "missing fragment: $fpath" >&2; exit 4; }
        cat "$CHESTER_ROOT/$fpath"
      else
        local sfile sheading body
        sfile="$(jq -r ".agents[$idx].fragments[$i].file" "$MANIFEST")"
        sheading="$(jq -r ".agents[$idx].fragments[$i].section" "$MANIFEST")"
        [ -f "$CHESTER_ROOT/$sfile" ] || { echo "missing fragment source: $sfile" >&2; exit 4; }
        body="$(extract_section "$CHESTER_ROOT/$sfile" "$sheading")"
        [ -n "$body" ] || { echo "section not found: '$sheading' in $sfile" >&2; exit 4; }
        printf '%s\n' "$body"
      fi
      printf '\n'
    done
  } > "$tmp"
  mv "$tmp" "$dest"
}

emit_catalog() {
  [ "$(jq -r '.catalog' "$MANIFEST")" != "null" ] || return 0
  local out tmpl tmpl_abs dest list glob
  out="$(jq -r '.catalog.output' "$MANIFEST")"
  tmpl="$(jq -r '.catalog.template' "$MANIFEST")"
  tmpl_abs="$CHESTER_ROOT/$tmpl"
  glob="$(jq -r '.catalog.scan_glob' "$MANIFEST")"
  dest="$OUT_DIR/$out"; mkdir -p "$(dirname "$dest")"
  [ -f "$tmpl_abs" ] || { echo "catalog template not found: $tmpl_abs" >&2; exit 4; }
  # Build the flat, alphabetically-sorted list of "- **name** — description" from each SKILL.md frontmatter.
  list="$(
    for f in "$CHESTER_ROOT"/$glob; do
      [ -f "$f" ] || continue
      local name desc
      name="$(awk '/^---$/{c++; next} c==1 && /^name:/{sub(/^name:[ ]*/,""); print; exit}' "$f")"
      # description may be inline ("description: text", optionally quoted) OR a YAML
      # folded/literal block scalar ("description: >" / "| " then indented continuation
      # lines). 9 of Chester's SKILL.md files use the folded form, so fold the
      # continuation lines into one space-joined line for the catalog entry.
      desc="$(awk '
        /^---$/ { c++; next }
        c==1 && /^description:/ {
          val = $0; sub(/^description:[ \t]*/, "", val)
          if (val ~ /^[>|]/) {
            d = ""
            while ((getline line) > 0) {
              if (line ~ /^---$/) break
              if (line ~ /^[ \t]*$/) continue
              if (line !~ /^[ \t]/) break
              sub(/^[ \t]+/, "", line)
              d = (d == "" ? line : d " " line)
            }
            print d
          } else {
            gsub(/^["'"'"']|["'"'"']$/, "", val); print val
          }
          exit
        }
      ' "$f")"
      [ -n "$name" ] && printf '%s\t%s\n' "$name" "$desc"
    done | LC_ALL=C sort | awk -F'\t' '{printf "- **%s** — %s\n", $1, $2}'
  )"
  # Splice the list into the template slot (replace the CATALOG_SLOT marker line).
  local tmp; tmp="$(mktemp)"
  awk -v list="$list" '/<!-- CATALOG_SLOT -->/{print list; next} {print}' "$tmpl_abs" > "$tmp"
  mv "$tmp" "$dest"
}

if [ "$MODE" = "all" ] || [ "$MODE" = "agents" ]; then
  count="$(jq -r '.agents | length' "$MANIFEST")"
  for (( n=0; n<count; n++ )); do emit_agent "$n"; done
fi
if [ "$MODE" = "all" ] || [ "$MODE" = "catalog" ]; then
  emit_catalog
fi
