#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CHESTER_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_DIR=""; MODE="all"
while [ $# -gt 0 ]; do
  case "$1" in
    --root) CHESTER_ROOT="$(cd "$2" && pwd)"; shift 2 ;;
    --output-dir) OUT_DIR="$2"; shift 2 ;;
    --agents-only) MODE="agents"; shift ;;
    --catalog-only) MODE="catalog"; shift ;;
    *) echo "chester-generate-agents: unknown arg: $1" >&2; exit 2 ;;
  esac
done
[ -n "$OUT_DIR" ] || OUT_DIR="$CHESTER_ROOT"
MANIFEST="$CHESTER_ROOT/agents/manifest.json"
command -v jq >/dev/null 2>&1 || { echo "chester-generate-agents: jq required" >&2; exit 3; }
[ -f "$MANIFEST" ] || { echo "chester-generate-agents: manifest not found: $MANIFEST" >&2; exit 3; }

HEADER='<!-- generated by bin/chester-generate-agents — edit canonical sources under agents/sources/, not this file -->'

# extract_section FILE "Heading" → body lines between "## Heading" and the next "## " (exclusive),
# with leading blank lines after the heading stripped (F6) so a blank line under the heading
# does not produce a double blank in the assembled output.
extract_section() {
  awk -v h="## $2" '
    $0==h { flag=1; started=0; next }
    flag && /^## / { flag=0 }
    flag {
      if (!started && $0 ~ /^[[:space:]]*$/) next
      started=1
      print
    }' "$1"
}

emit_agent() {
  local idx="$1" out frontmatter nfrag i ftype
  out="$(jq -r ".agents[$idx].output" "$MANIFEST")"
  frontmatter="$(jq -r ".agents[$idx].frontmatter" "$MANIFEST")"
  local dest="$OUT_DIR/$out"; mkdir -p "$(dirname "$dest")"
  local tmp; tmp="$(mktemp)"
  trap 'rm -f "$tmp"' RETURN  # clean the temp file on any exit from this function (incl. fragment-not-found)
  {
    printf '%s\n' "$HEADER"
    printf '%s\n' "$frontmatter"
    nfrag="$(jq -r ".agents[$idx].fragments | length" "$MANIFEST")"
    for (( i=0; i<nfrag; i++ )); do
      ftype="$(jq -r ".agents[$idx].fragments[$i] | if type==\"string\" then \"file\" else \"section\" end" "$MANIFEST")"
      if [ "$ftype" = "file" ]; then
        local fpath; fpath="$(jq -r ".agents[$idx].fragments[$i]" "$MANIFEST")"
        [ -f "$CHESTER_ROOT/$fpath" ] || { echo "missing fragment: $fpath" >&2; exit 4; }
        cat "$CHESTER_ROOT/$fpath"
      else
        local sfile sheading body
        sfile="$(jq -r ".agents[$idx].fragments[$i].file" "$MANIFEST")"
        sheading="$(jq -r ".agents[$idx].fragments[$i].section" "$MANIFEST")"
        [ -f "$CHESTER_ROOT/$sfile" ] || { echo "missing fragment source: $sfile" >&2; exit 4; }
        body="$(extract_section "$CHESTER_ROOT/$sfile" "$sheading")"
        [ -n "$body" ] || { echo "section not found: '$sheading' in $sfile" >&2; exit 4; }
        printf '%s\n' "$body"
      fi
      printf '\n'
    done
  } > "$tmp"
  mv "$tmp" "$dest"
}

if [ "$MODE" = "all" ] || [ "$MODE" = "agents" ]; then
  count="$(jq -r '.agents | length' "$MANIFEST")"
  for (( n=0; n<count; n++ )); do emit_agent "$n"; done
fi
# catalog mode added in Task 2
