#!/usr/bin/env bash
# tests/test-generate-agents-core.sh
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
GEN="$SCRIPT_DIR/bin/chester-generate-agents"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
ERRORS=0; fail() { echo "FAIL: $1" >&2; ERRORS=$((ERRORS+1)); }

# Fixture canonical sources
mkdir -p "$TMP/agents/sources" "$TMP/agents" "$TMP/skills/x"
printf 'SHARED-BAND\n' > "$TMP/agents/sources/scaffold.md"
# Section fixture includes a leading blank after the heading to prove F6 (leading-blank strip).
printf '## Body\n\nLINE-A\nLINE-B\n## Next\nIGNORED\n' > "$TMP/skills/x/SKILL.md"
# Fixture manifest: one agent, one whole-file fragment + one section fragment
cat > "$TMP/agents/manifest.json" <<'JSON'
{ "agents": [ { "output": "agents/out.md",
    "frontmatter": "---\nname: out\n---",
    "fragments": [ "agents/sources/scaffold.md", {"file":"skills/x/SKILL.md","section":"Body"} ] } ],
  "catalog": null }
JSON

# Run generator against the fixture root (generator resolves root from --root)
"$GEN" --root "$TMP" --agents-only

EXPECTED=$'<!-- generated by bin/chester-generate-agents — edit canonical sources under agents/sources/, not this file -->\n---\nname: out\n---\nSHARED-BAND\n\nLINE-A\nLINE-B\n\n'
# Read with trailing newlines preserved — bare $(cat) strips them and would
# falsely mismatch the trailing blank EXPECTED carries.
ACTUAL="$(cat "$TMP/agents/out.md"; printf x)"; ACTUAL="${ACTUAL%x}"
[ "$ACTUAL" = "$EXPECTED" ] || fail "generated bytes mismatch:\n$ACTUAL"

# Determinism: second run identical
"$GEN" --root "$TMP" --agents-only
ACTUAL2="$(cat "$TMP/agents/out.md"; printf x)"; ACTUAL2="${ACTUAL2%x}"
[ "$ACTUAL2" = "$EXPECTED" ] || fail "non-deterministic second run"

[ "$ERRORS" -eq 0 ] && echo "PASS: test-generate-agents-core" || { echo "FAIL: test-generate-agents-core" >&2; exit 1; }
